routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use \App\Http\Controllers\CategoryController;
use App\Http\Controllers\ClothTrashController;
use \App\Http\Controllers\CategoryTrashController;
use App\Http\Controllers\DashboardClothController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');
});

Route::get('/woman', function () {
    return view('landing-woman');
});
Route::get('/detail-product', function (){
    return view('product-detail');
});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::middleware(['auth', 'admin'])->group(function() {
    Route::get('/dashboard', function(){
        return view('admin.index');
    });
    Route::resource('dashboard/cloth', DashboardClothController::class);
    Route::controller(ClothTrashController::class)->group(function () {
        Route::get('/dashboard/trash/cloth', 'index')->name('cloth-trash.index');
        Route::post('/dashboard/trash/cloth/{cloth}', 'restore')->name('cloth-trash.restore');
        Route::post('/dashboard/trash/cloth/{cloth}/delete', 'destroy')->name('cloth-trash.delete');
    });
    Route::resource('dashboard/category', CategoryController::class);
    Route::controller(CategoryTrashController::class)->group(function () {
        Route::get('/dashboard/trash/category', 'index')->name('category-trash.index');
        Route::post('/dashboard/trash/category/{category}', 'restore')->name('category-trash.restore');
        Route::post('/dashboard/trash/category/{category}/delete', 'destroy')->name('category-trash.delete');
    });
});

app/Models/Cloth.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Cloth extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $guarded = ['id'];

    public function category() {
        return $this->belongsTo(Category::class);
    }
}

resources/views/admin/cloth/createCloth.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard | Create Cloth')

@section('content_header')
    <h1>Add New Cloth</h1>
@stop

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-8">
        <form action="{{ route('cloth.store') }}" method="POST" class="d-inline" enctype="multipart/form-data">
            @csrf
            <div class="mb-3">
                <label for="image">Image Cloth : </label>
                {{-- <img src="{{ $cloth->image }}" id="image" name="image" alt="image" width="400" class="d-block mb-3"> --}}
                <label class="block mb-4">
                    <span class="sr-only">Choose File</span>
                    <input type="file" name="image"
                        class="custom-file block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100" />
                    @error('image')
                        <p class="invalid-feedback">{{ $message }}</p>
                    @enderror
                </label>
            </div>
            <div class="mb-3">
                <label for="name">Category Cloth : </label>
                <select class="form-control" id="exampleFormControlSelect1" name="category_id">
                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}">
                                {{ $category->name }}
                        </option>
                    @endforeach
                  </select>
            </div>
            <div class="mb-3">
                <label for="name">Name Cloth : </label>
                <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}"></input>
            </div>
            <div class="mb-3">
                <label for="stock">Stock Cloth : </label>
                <input type="text" class="form-control" id="stock" name="stock" value="{{ old('stock') }}"></input>
            </div>
            <div class="mb-3">
                <label for="price">Price Cloth : </label>
                <input type="text" class="form-control" id="price" name="price" value="{{ old('price') }}"></input>
            </div>
            <div class="mb-3">
                <label for="description">Description Cloth : </label>
                <textarea id="description" name="description" rows="15" cols="88">
                    {{ old('description') }}
                </textarea>

            </div>
            <a href="/dashboard/cloth" class="btn btn-dark mb-4">Back</a>

            <button type="submit" class="btn btn-warning mb-4">Add new Cloth</button>
            </form>
        </div>
    </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.13.1/datatables.min.css"/>
@stop

@section('js')
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.13.1/datatables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table_id').DataTable();
        });
    </script>
@stop

resources/views/admin/cloth/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard | Cloth Edit')

@section('content_header')
    <h1>Edit Cloth</h1>
@stop

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-8">
        <form action="{{ route('cloth.update', $cloth) }}" method="POST" class="d-inline" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="mb-3">
                <label for="image">Image Cloth : </label>
                <img src="{{ $cloth->image }}" id="image" name="image" alt="image" width="400" class="d-block mb-3">
                <label class="block mb-4">
                    <span class="sr-only">Choose File</span>
                    <input type="file" name="image"
                        class="custom-file block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100" />
                    @error('image')
                        <p class="invalid-feedback">{{ $message }}</p>
                    @enderror
                </label>
            </div>
            <div class="mb-3">
                <label for="name">Category Cloth : </label>
                <select class="form-control" id="exampleFormControlSelect1" name="category_id">
                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}">
                                {{ $category->name }}
                        </option>
                    @endforeach
                  </select>
            </div>
            <div class="mb-3">
                <label for="name">Name Cloth : </label>
                <input type="text" class="form-control" id="name" name="name" value="{{ $cloth->name }}"></input>
            </div>
            <div class="mb-3">
                <label for="stock">Stock Cloth : </label>
                <input type="text" class="form-control" id="stock" name="stock" value="{{ $cloth->stock }}"></input>
            </div>
            <div class="mb-3">
                <label for="price">Price Cloth : </label>
                <input type="text" class="form-control" id="price" name="price" value="{{ $cloth->price }}"></input>
            </div>
            <div class="mb-3">
                <label for="description">Description Cloth : </label>
                <textarea id="description" name="description" rows="15" cols="88">
                    {{ $cloth->description }}
                </textarea>

            </div>
            <a href="/dashboard/cloth" class="btn btn-dark mb-4">Back</a>

            <button type="submit" class="btn btn-warning mb-4">Update</button>
            </form>
        </div>
    </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
@stop

resources/views/admin/cloth/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard | Cloth Edit')

@section('content_header')
    {{-- <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard Posts</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar" class="align-text-bottom"></span>
            This week
        </button>
        </div>
    </div> --}}
    <h1>Cloth List</h1>
@stop

@section('content')
    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-block" role="alert">
            <strong>{{$message}}</strong>
        </div>

        <img src="{{ asset('images/'.Session::get('image')) }}" />
    @endif
    <table id="table_id" class="dataTable table table-bordered">
        <thead>
        <tr>
            <th>No.</th>
            <th>Cloth Name</th>
            <th>Stock Avaible</th>
            <th>Price</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($cloths as $cloth)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $cloth->name }}</td>
                    <td>{{ $cloth->stock }}</td>
                    <td>{{ $cloth->price }}</td>
                    <td>{{ Str::limit($cloth->description) }}</td>
                    <td class="d-flex">
                        <a href="/dashboard/cloth/{{ $cloth->id }}" class="btn btn-dark h-100">Show</a>
                        <a href="/dashboard/cloth/{{ $cloth->id }}/edit" class="btn btn-warning h-100 mx-1">Edit</a>
                        <form action="{{ route('cloth.destroy', $cloth->id) }}" method="POST" class="d-inline-block">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">
                                Delete
                            </button>
                        </form>
                    </td>
                </tr>
                @endforeach
        </tbody>
    </table>

    <p>Page for change Cloth.</p>
    <div class="container">
        <div class="row">
            <div class="col-md-4 p-1 mb-3">
                <div class="card">
                    <img src="https://source.unsplash.com/800x400?" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">Card title</h5>
                      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                      <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
            <div class="card" style="width: 18rem;">
                <img src="https://source.unsplash.com/800x400?" class="card-img-top" alt="...">
                <div class="card-body">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.13.1/datatables.min.css"/>
@stop

@section('js')
    <script src="{{ asset('js/app.js') }}"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.13.1/datatables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table_id').DataTable();
        });
        const alertList = document.querySelectorAll('.alert')
        const alerts = [...alertList].map(element => new bootstrap.Alert(element))
    </script>
@stop

resources/views/admin/cloth/show.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard | Cloth Edit')

@section('content_header')
    <h1>Show Cloth</h1>
@stop

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="mb-3">
                <label for="name">Image Cloth : </label>
                <img src="{{ asset('storage/'.$cloth->image) }}" id="image" name="image" alt="image" width="400" class="d-block">
            </div>
            <div class="mb-3">
                <label for="name">Category Cloth : </label>
                <p>{{ $cloth->category_id }}</p>
            </div>
            <div class="mb-3">
                <label for="name">Name Cloth : </label>
                <p>{{ $cloth->name }}</p>
            </div>
            <div class="mb-3">
                <label for="name">Stock Cloth : </label>
                <p>{{ $cloth->stock }}</p>
            </div>
            <div class="mb-3">
                <label for="name">Price Cloth : </label>
                <p>{{ $cloth->price }}</p>
            </div>
            <div class="mb-3">
                <label for="name">Description Cloth : </label>
                <p>{{ $cloth->description }}</p>
            </div>
            <a href="/dashboard/cloth" class="btn btn-dark mb-4">Back</a>
        </div>
    </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
@stop

resources/views/admin/cloth/trashCloth.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard | Cloth Edit')

@section('content_header')
    <h1>Cloth Trash</h1>
@stop

@section('content')
    <div class="container">
        {{-- @if(session()->has('restore-success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Great!</strong> {{ session('restore-success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @elseif(session()->has('delete-success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Great!</strong> {{ session('delete-success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif --}}
        <table id="table_id" class="dataTable table table-bordered">
            <thead>
            <tr>
                <th>No.</th>
                <th>Cloth Name</th>
                <th>Cloth Stock</th>
                <th>Cloth Price</th>
                <th>Cloth Dsscription</th>
                <th>Deleted At</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($cloths as $cloth)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $cloth->name }}</td>
                    <td>{{ $cloth->stock }}</td>
                    <td>{{ $cloth->price }}</td>
                    <td>{{ $cloth->stock }}</td>
                    <td>{{ Str::limit($cloth->description) }}</td>
                    <td>{{ $cloth->deleted_at->diffForHumans() }}</td>
                    <td class="d-flex">
                        <form action="{{ route('cloth-trash.restore', $cloth->id) }}" method="POST" class="d-inline-block mx-3">
                            @csrf
                            <button type="submit" class="btn btn-success">
                                Restore
                            </button>
                        </form>
                        <form action="{{ route('cloth-trash.delete', $cloth->id) }}" method="POST" class="d-inline-block mx-3" onsubmit="return confirm('This action will permanently delete this category. Do you wish to continue?')">
                            @csrf
                            <button type="submit" class="btn btn-danger">
                                Delete
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@stop

@section('css')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.13.1/datatables.min.css"/>
@stop

@section('js')
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.13.1/datatables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table_id').DataTable();
        });
    </script>
@stop